[book]
title = "Atomic Data"
authors = ["Joep Meindertsma"]
description = "Documentation for the Atomic Data standard."
language = "en"

[output.html]
google-analytics = "123456"
git-repository-url = "https://github.com/ontola/atomic-data"
git-repository-icon = "fa-github"
